import json,copy,shutil,hashlib
from pathlib import Path
R=Path.cwd();O=R/'audit/production_3sinf'; updates={}; cache={}; events=[]
def patch(subject,prefix,n,s=None,v=None,a=None,reason='Savolni bir ma’noli, ravon va mustaqil yechiladigan qilish'):
 folder=R/'3-sinf'/f'3-sinf 3-Sinf {subject}'; ps=list(folder.glob(prefix+'_*.json'));assert len(ps)==1,(subject,prefix)
 p=ps[0];d=cache.setdefault(p,json.loads(p.read_text(encoding='utf-8')));q=d['savollar'][n-1];old=copy.deepcopy(q)
 if s is not None:q['savol']=s
 if v is not None:q['variantlar']=v
 if a is not None:q['togri']=a
 assert len(q['variantlar'])==4 and len(set(q['variantlar']))==4
 if old!=q:events.append({'file':p.relative_to(R).as_posix(),'question_no':n,'before':old,'after':copy.deepcopy(q),'reason':reason})
def eng(t,n,s=None,v=None,a=None):patch('Ingliz tili',f'{t:03}',n,s,v,a)
# Mathematics: retain the original objective, make assumptions explicit.
patch('Matematika','003',26,"370 + 270 + 230 ni hisoblashda avval yig'indisi 600 bo'ladigan ikki son qo'shilsin. Qaysi variant shu usul va to'g'ri yakuniy natijani ko'rsatadi?")
patch('Matematika','022',12,"Supermarketga 20 ta yashikda jami 400 shisha suv keltirildi. Har bir yashikda suv shishalari soni teng. Har bir yashikda nechta shisha suv bor?")
patch('Matematika','022',22,"Oygul Malikadan kichik, Zebo esa Oyguldan kichik. Uchalasidan kim eng kichik?")
patch('Matematika','028',23,"Avtomobil odometri avval 540 km ni, 3 soatdan so'ng 750 km ni ko'rsatdi. Avtomobil o'zgarmas tezlikda harakatlansa, 4 soatda necha kilometr yuradi?")
patch('Matematika','028',24,"Avtomobil odometri avval 540 km ni, 3 soatdan so'ng 750 km ni ko'rsatdi. Shu o'zgarmas tezlikda avtomobil 490 km ni necha soatda bosib o'tadi?")
patch('Matematika','050',2,"Noldan farqli sonlarni ko'paytirish natijasini qanday tekshirish mumkin?")
patch('Matematika','051',1,"Noldan farqli sonlarni ko'paytirish natijasini qanday tekshirish mumkin?")
patch('Matematika','056',3,"Piyoda o'zgarmas tezlikda 4 soatda 20 km yo'l yurdi. U 1 soatda necha kilometr yurgan?")
patch('Matematika','056',4,"Avtomobil o'zgarmas tezlikda 3 soatda 360 km yo'l bosdi. U 1 soatda necha kilometr yurgan?")
patch('Matematika','057',1,"Piyoda o'zgarmas tezlikda 4 soatda 20 km yo'l yurdi. U 1 soatda necha kilometr yurgan?")
patch('Matematika','062',21,"Tortning yarmi Munisa va Shoiraga birgalikda, butun tortning choragi esa Mustafoga berildi. Tortning qancha qismi qoldi?")
patch('Matematika','073',21,"Uyning har bir yo'lagida xonadonlar soni teng. Uning 3 ta yo'lagida jami 54 ta xonadon bo'lsa, 7 ta yo'lagida jami nechta xonadon bor?")
patch('Matematika','078',8,"Qoldiqsiz bo'lishda bo'linma va bo'luvchi yordamida bo'linuvchini topish uchun qaysi amal bajariladi?")
patch('Matematika','080',2,v=["Uchburchakning gipotenuzasiga","Uchburchakning perimetriga","Uchburchakning aylanish o'qi bo'lmagan ikkinchi katetiga","Doiraning yuziga"])
# English, lesson 1: distinguish siblings from total family size and age.
eng(1,1,v=["Mening ikkita opa-singlim bor","Mening bitta opa-singlim bor","Mening uchta opa-singlim bor","Mening ikkita aka-ukam bor"])
eng(1,4,v=["Mening bitta opa-singlim bor","Mening ikkita opa-singlim bor","Mening bitta aka-ukam bor","Mening ikkita aka-ukam bor"])
eng(1,5,"'I have two sisters' gapida nima haqida aytilgan?",["Sevimli rang haqida","Maktab haqida","Kasb haqida","Opa-singillar soni haqida"])
for n,w in [(6,'Two'),(7,'Three'),(9,'One')]:eng(1,n,f"'{w}' so'zi qaysi sonni bildiradi?")
eng(1,10,"'One, two, three' so'zlarini mashq qilish nimani o'rganishga yordam beradi?",["Kasblarni","Hayvonlarni","Ranglarni","Sonlarni"])
eng(1,11,"'I have one sister' gapida nechta opa yoki singil borligi aytilgan?")
for n,s in [(12,'I have two sisters and one brother'),(13,'I have two brothers and two sisters'),(14,'I have three sisters and one brother'),(16,'I have one sister and one brother'),(17,'I have three brothers and one sister')]:eng(1,n,f"'{s}' gapida so'zlovchining aka-uka va opa-singillari jami nechta?")
eng(1,15,"'I have one brother and three sisters' gapida nechta opa yoki singil borligi aytilgan?")
eng(1,18,"'Mening ikkita opa-singlim bor' ingliz tilida qanday aytiladi?")
eng(1,19,"'I have one sister and two brothers' gapida nechta aka yoki uka borligi aytilgan?")
eng(1,21,"'I have three sisters and one brother' gapida qaysi ikki turdagi so'zlar ishlatilgan?",["Faqat ranglar","Faqat kasblar","Kasblar va ranglar","Sonlar va qarindoshlik nomlari"])
eng(1,23,"Ali 'I have two sisters and one brother', Vali 'I have one sister and two brothers' dedi. Ali va Vali turli oilalardan. Ular sanagan aka-uka va opa-singillar jami nechta?")
eng(1,25,"'Look at the pictures and match' ko'rsatmasi nimani bildiradi?",["Faqat yozing","Faqat o'qing","Faqat tinglang","Rasmlarga qarang va moslashtiring"])
eng(1,26,"Bir bolaning aka-uka va opa-singillari jami 4 nafar. Aka-ukalar soni 0, 1, 2, 3 yoki 4 bo'lishi mumkin. Ularning sonlarini taqsimlashning nechta varianti bor?")
eng(1,28,"'Work in groups of four' ko'rsatmasiga ko'ra har bir guruhda nechta o'quvchi bo'ladi?",a=1)
eng(1,29,"'Three sisters and two brothers' iborasida jami nechta kishi sanalgan?")
eng(1,30,"'I have two sisters' va 'I have one brother' gaplari yordamida nimalar mashq qilinadi?",["Faqat hayvon nomlari","Sonlar va qarindoshlik nomlari","Faqat ranglar","Faqat kasblar"])
# English, lesson 2: remove corrupted translations and unspecified game rules.
eng(2,1,"'My mum is a teacher' gapining tarjimasini toping.",["Mening otam shifokor","Mening onam oshpaz","Mening onam o'qituvchi","Mening akam haydovchi"])
eng(2,2,"'Listen and repeat' ko'rsatmasining tarjimasini toping.",["Tinglang va takrorlang","Ko'rsating va ayting","O'qing va yozing","Tinglang va qo'shiq ayting"])
eng(2,3,"'My mum is a teacher' gapida qaysi kasb nomi bor?")
eng(2,5,"Ingliz tilida birlikdagi kasb nomidan oldin, masalan, 'She is ... teacher' gapida qaysi turdagi artikl qo'llanadi?")
eng(2,6,"'Point and say' ko'rsatmasining tarjimasini toping.",["O'qing va yozing","Tinglang va takrorlang","Ko'rsating va ayting","Chizing va bo'yang"])
eng(2,7,"'Teacher' kasbidagi kishi nima qiladi?",["Yong'inni o'chiradi","Avtomobil boshqaradi","Ekin yetishtiradi","Dars beradi"])
eng(2,8,"'Driver' kasbidagi kishi nima qiladi?",["Avtomobil boshqaradi","Dars beradi","Bemorlarni davolaydi","Ovqat tayyorlaydi"])
eng(2,9,"'Work in pairs' ko'rsatmasi nimani bildiradi?",["Butun sinf bilan ishlang","Juftlikda ishlang","To'rt kishilik guruhda ishlang","Yolg'iz ishlang"])
eng(2,11,"Kasbi avtomobil boshqarish bo'lgan kishi ingliz tilida kim deyiladi?")
eng(2,12,"O'quvchilarga dars beradigan mutaxassis ingliz tilida kim deyiladi?")
eng(2,13,"O'z xo'jaligida ekin yetishtiradigan fermer ingliz tilida kim deyiladi?")
eng(2,14,"Ovqat tayyorlaydigan oshpaz ingliz tilida kim deyiladi?")
eng(2,15,"Yong'inni o'chiradigan mutaxassis ingliz tilida kim deyiladi?")
eng(2,16,"Bemorlarni davolaydigan shifokor ingliz tilida kim deyiladi?")
eng(2,17,"Kotib ingliz tilida qanday ataladi?")
eng(2,18,"Samolyotni boshqaradigan uchuvchi ingliz tilida kim deyiladi?")
eng(2,19,"'Teacher', 'doctor' va 'driver' so'zlari qaysi mavzuga kiradi?",["Hayvonlar","Ranglar","Sonlar","Kasblar"])
eng(2,20,"'Listen and sing' ko'rsatmasining tarjimasini toping.",["Tinglang va qo'shiq ayting","Ko'rsating va ayting","O'qing va yozing","Tinglang va takrorlang"])
eng(2,21,"'My dad is a doctor' va 'My mum is a teacher' gaplarida qaysi ikki kasb aytilgan?",["Oshpaz va fermer","Haydovchi va uchuvchi","Kotib va o't o'chiruvchi","Shifokor va o'qituvchi"])
eng(2,22,"O'yin qoidasi: bir o'quvchi kasbni gapirmasdan harakat bilan ko'rsatadi, boshqalar topadi. Kasbni ko'rsatuvchi o'quvchi nima qiladi?",["Kasb nomini yozadi","Kasb nomini aytadi","Boshqalarning javobini takrorlaydi","Kasbga mos harakatlarni bajaradi"])
eng(2,23,"'Write in alphabetical order' ko'rsatmasining tarjimasini toping.",["So'zlarni teskari yozing","Faqat bosh harflar bilan yozing","So'zlarni tarjima qiling","Alifbo tartibida yozing"])
eng(2,25,"'Farmer' kasbidagi kishi odatda qaysi ish bilan shug'ullanadi?",["Ekin yetishtirish va chorva boqish","Maktabda dars berish","Samolyot boshqarish","Yong'inni o'chirish"])
eng(2,26,"'My sister is a ...' gapiga grammatik jihatdan qaysi so'z mos keladi?",["teacher","apples","happy","run"])
eng(2,27,"'Cook', 'pilot' va 'farmer' so'zlarini o'rganishdan maqsad nima?",["Sonlarni o'rganish","Hayvonlarni o'rganish","Kasb nomlarini o'rganish","Ranglarni o'rganish"])
eng(2,28,"'Listen and sing' hamda 'Listen and repeat' ko'rsatmalarining farqi nima?",["Birinchisida qo'shiq aytiladi, ikkinchisida eshitilgan gap yoki so'z takrorlanadi","Birinchisida rasm chiziladi","Ikkalasi ham faqat yozishni talab qiladi","Ikkinchisida albatta raqs tushiladi"])
eng(2,29,"Inglizcha matnlardagi 'e.g.' qisqartmasi qanday ma'noda qo'llanadi?")
eng(2,30,"'Doctor', 'director', 'cook', 'driver' so'zlari alifbo tartibida joylashtirilsa, qaysi biri birinchi keladi?")
# English, lesson 3: one valid answer and enough context for every reviewed question.
eng(3,2,"'Engineer' so'zining o'zbekcha tarjimasi qaysi?",["Shifokor","Haydovchi","Muhandis","O'qituvchi"])
eng(3,3,"Qaysi savolga qisqa tasdiq javobi sifatida 'Yes, I am' deyish mumkin?",["Are you in the library?","Do you like apples?","What is your name?","Is he happy?"])
eng(3,4,"'Are you in the gym?' savoliga qisqa tasdiq javobini toping.",["Yes, I am.","Yes, he is.","Yes, they are.","Yes, she is."])
eng(3,5,"'His mum's a teacher' gapida kim o'qituvchi?",["Uning otasi","Uning akasi","Uning singlisi","Uning onasi"])
eng(3,6,"'Park' so'zining o'zbekcha tarjimasi qaysi?",["Istirohat bog'i","Shifoxona","Muzey","Aeroport"])
eng(3,7,"'School' so'zining o'zbekcha tarjimasi qaysi?",["Kutubxona","Istirohat bog'i","Sport zali","Maktab"])
eng(3,10,"'I am ... the library' gapida kutubxona ichida ekanlikni bildiruvchi predlogni tanlang.",["under","by","on","in"])
eng(3,12,"'My mum's a teacher' gapini 'His mum's a teacher' shakliga o'tkazishda qaysi so'z almashtiriladi?",["teacher so'zi doctor bilan","mum so'zi dad bilan","a artikli the bilan","My so'zi His bilan"])
eng(3,13,"O'yin qoidasi: A kartadagi kasbni harakat bilan ko'rsatadi, B kasbni topadi. A nima qilishi kerak?",["Joy nomini aytishi","Kartadagi kasbga mos harakatni ko'rsatishi","Ismini aytishi","Kasb nomini yozishi"])
eng(3,15,"'I am ... gym' gapida sport zali ichida ekanlikni bildirish uchun qaysi birikma kerak?",["by a","in the","under the","on a"])
eng(3,16,"Ali otasi haqida gapirdi. Vali Alini nazarda tutib 'His dad's a doctor' dedi. Ali avval qaysi gapni aytgan?")
eng(3,17,"'Are you in the canteen?' savoliga qisqa tasdiq javobini toping.")
eng(3,19,"Bola 'My mum's a teacher' dedi. Uning onasi haqida 'His mum's a teacher' deyishda nima o'zgaradi?",["Kasb nomi","Joy nomi","mum so'zi","My so'zi His so'ziga almashtiriladi"])
eng(3,20,v=["Kutubxonada","Istirohat bog'ida","Hayvonot bog'ida","Sport zalida"])
eng(3,21,"Ali: 'My dad's a driver.' Vali Ali haqida: 'His dad's a ___.' Bo'sh joyni inglizcha so'z bilan to'ldiring.",["driver","teacher","doctor","engineer"])
eng(3,23,"Suhbatdoshingizning o'qituvchi ekanini so'rash uchun qaysi savol mos keladi?")
eng(3,24,v=["Birinchisi tasdiq gap, ikkinchisi inkor gap","Birinchisi joyni, ikkinchisi kasbni so'raydi","Birinchisi yoshni, ikkinchisi ismni so'raydi","Birinchisi rangni, ikkinchisi sonni so'raydi"])
eng(3,25,"Ali ismli o'g'il bola: 'My mum's a teacher, my dad's a doctor' dedi. Vali Alining ota-onasi haqida qaysi gapni aytadi?")
eng(3,26,"'Are you in the gym?' savolida nima so'ralgan?",["Sport zalida ekaningiz","Kasbingiz","Yoshingiz","Ismingiz"])
eng(3,27,"Ali 'My mum's a teacher' dedi. Shu gapni Ali haqida 'His mum's a teacher' deb aytish uchun qaysi o'zgarish qilinadi?")
eng(3,28,"Odamlar turli hayvonlarni tomosha qilish uchun boradigan joy qaysi?",["Oshxona","Kutubxona","Sinf xonasi","Hayvonot bog'i"])
eng(3,29,"'Yes, I am' yoki 'No, I'm not' qisqa javoblari qaysi turdagi savolga mos keladi?",["Are you ...? bilan boshlangan savolga","Do you ...? bilan boshlangan savolga","Where is ...? bilan boshlangan savolga","How many ...? bilan boshlangan savolga"])
eng(3,30,"'Are you a driver?' — 'Yes, I am' suhbati qanday ko'nikmani mashq qildiradi?",["Sonlarni hisoblash","Kasb haqida so'rash va qisqa javob berish","Joy nomlarini yozish","Ranglarni farqlash"])
# Save a reviewable plan before applying any source changes.
(O/'changes_plan.json').write_text(json.dumps(events,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for p,d in cache.items():
 rel=p.relative_to(R);b=O/'backup'/rel;b.parent.mkdir(parents=True,exist_ok=True)
 if not b.exists():shutil.copy2(p,b)
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(O/'changes_applied.json').write_text(json.dumps(events,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Changed questions',len(events),'files',len(cache))
