from pathlib import Path
p=Path('audit/production_3sinf/build_status.py');s=p.read_text(encoding='utf-8')
s=s.replace("rows=[];subjects=[]", "source_path=O/'local_source_reviews.json'\nsource_refs={(x['file'],x['question_no']):x for x in json.loads(source_path.read_text(encoding='utf-8')) if x['question_no'] is not None} if source_path.exists() else {}\nrows=[];subjects=[]")
s=s.replace("   rows.append({'file':rel", "   ref=source_refs.get(key)\n   if ref and ref['sha256']==h:\n    state='joriy_tekshirildi';proof='Mahalliy darslik: '+ref['source_file']+'; PDF betlari '+str(ref['pdf_pages'])+'; local_source_reviews.json'\n   rows.append({'file':rel")
s=s.replace("'Darslik nashri va manbalar tasdiqlanmagan'", "'Barcha mavzular hali mahalliy darsliklar bilan solishtirilmagan'")
s=s.replace("'Ona tili testlari mavjud emas'", "'Ona tili va Musiqa testlari mavjud emas'")
s=s.replace("'3-sinf Musiqa: joriy papka mavjud emas; amaldagi darslik ro‘yxati bilan to‘liqlikni tasdiqlash kerak'", "'3-sinf Musiqa: mahalliy PDF mavjud, test papkasi mavjud emas'")
s=s.replace('18 savolda shart va ifodalar aniqlandi.', '24 savolda shart va ifodalar aniqlandi; 22 ta manbaga bog‘liq savol mahalliy Matematika (2019) darsligi bilan solishtirildi.')
s=s.replace('Qolgan kitoblar bo‘yicha rasmiy ro‘yxat va nashr yili berilmagani uchun barcha zarur darsliklar qamrab olinganini tasdiqlab bo‘lmaydi.', 'Mahalliy kitoblar papkasi to‘liq inventarizatsiya qilindi. Barcha sinflar bo‘yicha testi yo‘q 42 kitob TESTI_YOQ_KITOBLAR.md da; 3-sinfda 11 kitobning 9 tasiga test bor.')
s=s.replace('Darsliklar nashri aniqlanmagan. Bir xil fan ichida parallel mavzu to‘plamlari bor;', 'Mahalliy darsliklar topildi. Bir xil fan ichida parallel mavzu to‘plamlari bor;')
s=s.replace('Matematikadagi 22 ta manbaga bog‘liq savol alohida ro‘yxatda. Ular o‘chirilmadi, tasdiqlangan deb belgilanmadi.', 'Matematikadagi 22 ta manbaga bog‘liq savol endi mahalliy darslik betlari bilan tekshirildi. Bet raqamlari va fayl mazmun izlari local_source_reviews.json da saqlandi.')
s=s.replace('Asl hikoya, rasm, jadval va darslik matnlari mavjud emas; ularni taxmin qilib almashtirish qilinmadi.', 'Mahalliy PDFlar mavjud; Ingliz tili, Ona tili va Musiqa kitoblari asosan skan sahifalardan iborat. Ularni sahifa tasviri orqali tekshirish mumkin. Manba yo‘qligi sababli ishni to‘xtatish uchun asos yo‘q.')
s=s.replace('1. Foydalaniladigan 3-sinf darsliklarining PDF yoki havolalari va nashr yilini olish.', '1. Faqat Test_Generator/kitoblar ichidagi mahalliy darsliklardan foydalanish; internetdan qidirmaslik.')
s=s.replace('manba_kerak.csv — matematikadagi aniqlangan manba talablari.', 'manba_kerak.csv — hali manba bilan tasdiqlanmagan qaydlar; dastlabki 22 matematika savoli mahalliy manba orqali yopildi.')
s=s.replace('2026-09-28: 91 savol tuzatildi;', '2026-09-28: 97 savol tuzatildi;')
s=s.replace('Mazmuniy tekshiruv davom ettirilishi va darslik manbalari kerak.', 'Mahalliy darsliklar topildi; mazmuniy tekshiruv davom ettirilishi kerak.')
p.write_text(s,encoding='utf-8')
